import type { PluginInfo } from '../path';
import type { IPCApiRequest, IPCReply, ParentToWorker } from './protocol';
type ReplyHandler = (reply: IPCReply) => void;
type ApiRequestHandler = (req: IPCApiRequest) => void;
declare class YunzaiManager {
    private worker;
    private ready;
    private replyHandlers;
    private doneHandlers;
    private apiRequestHandlers;
    private exitHandlers;
    private restartCount;
    private maxRestarts;
    private restartTimer;
    private taskName;
    private taskProcess;
    private taskCancelled;
    get isInstalled(): boolean;
    get isRunning(): boolean;
    get isReady(): boolean;
    getStatus(): string;
    get isBusy(): boolean;
    get busyTaskName(): string;
    get lastStartOk(): boolean;
    private markStartOk;
    private markStartFailed;
    cancelTask(): boolean;
    install(repoUrl?: string): Promise<void>;
    update(force?: boolean): Promise<string>;
    updateAll(force?: boolean): Promise<string>;
    start(): Promise<void>;
    stop(): Promise<void>;
    restart(): Promise<void>;
    installAndStart(repoUrl?: string): Promise<void>;
    uninstall(): Promise<void>;
    private syncRedisConfig;
    private startInternal;
    private stopInternal;
    send(msg: ParentToWorker): void;
    onReply(handler: ReplyHandler): () => void;
    onDone(handler: (done: any) => void): () => void;
    onApiRequest(handler: ApiRequestHandler): () => void;
    onWorkerExit(handler: (code: number | null) => void): () => void;
    sendToWorker(msg: ParentToWorker): void;
    private handleMessage;
    private beginTask;
    private endTask;
    private throwIfCancelled;
    private execGit;
    private npmInstall;
    installPlugin(plugin: PluginInfo): Promise<void>;
    updatePlugin(plugin: PluginInfo, force?: boolean): Promise<string>;
    uninstallPlugin(plugin: PluginInfo): void;
    installDeps(): Promise<string>;
    private ensureWorkspaces;
}
export declare const manager: YunzaiManager;
export {};
