import type { IPCEventMessage, ReplyContent } from '../protocol';
type CallApi = (action: string, params?: Record<string, any>, timeout?: number) => Promise<any>;
type SerializeReply = (msg: any) => Promise<ReplyContent[]>;
type WrapCompatValue = <T>(value: T, label: string) => T;
type SafeInt = (v: any, fallback: number) => number;
type ResolveMasterFlag = (data: IPCEventMessage['data']) => boolean;
type BuildForwardMsgCompat = (nodes: any[]) => any;
type OneBotBotState = {
    nickname: string;
    tiny_id: string;
    avatar: string;
    fl: Map<any, any>;
    gl: Map<any, any>;
    gml: Map<any, Map<any, any>>;
    stat: Record<string, any>;
    config?: Record<string, any>;
    status?: number;
    uin: any;
    _events?: Map<string, ((...args: any[]) => void)[]>;
    [key: string]: any;
};
type OneBotGroupOptions = {
    name?: string;
    is_owner?: boolean;
    is_admin?: boolean;
};
type BuildOneBotEventOptions = {
    data: IPCEventMessage['data'];
    msgId: string;
    selfId: number;
    reply: (msg: any, quote?: boolean) => any;
};
export declare function isOneBotPlatform(platform?: string): boolean;
export declare function createOneBotRuntime(deps: {
    callApi: CallApi;
    serializeReply: SerializeReply;
    wrapCompatValue: WrapCompatValue;
    safeInt: SafeInt;
    resolveMasterFlag: ResolveMasterFlag;
    buildForwardMsgCompat: BuildForwardMsgCompat;
}): {
    createOneBotBotAdapter: (state: OneBotBotState) => {
        getFriendMap: () => Map<any, any>;
        getGroupMap: () => Map<any, any>;
        pickFriend: (uid: number) => {
            user_id: number;
            readonly nickname: any;
            readonly remark: any;
            readonly info: any;
            readonly sex: any;
            readonly class_id: any;
            readonly class_name: any;
            asFriend: () => any;
            asMember: (gid: number) => {
                user_id: number;
                group_id: number;
                readonly card: any;
                readonly nickname: any;
                readonly remark: any;
                readonly title: any;
                readonly role: any;
                readonly level: any;
                readonly is_admin: boolean;
                readonly is_owner: boolean;
                is_friend: boolean;
                readonly mute_left: number;
                readonly _info: any;
                group: {
                    group_id: number;
                    readonly group_name: any;
                    readonly name: any;
                    readonly member_count: any;
                    readonly max_member_count: any;
                    is_owner: boolean;
                    is_admin: boolean;
                    mute_left: number;
                    sendMsg: (msg: any) => Promise<any>;
                    getMemberMap: () => Promise<Map<any, any>>;
                    pickMember: (uid: number) => any;
                    recallMsg: (messageId: any) => Promise<any>;
                    muteMember: (uid: number, duration?: number) => Promise<any>;
                    kickMember: (uid: number, rejectAdd?: boolean) => Promise<any>;
                    pokeMember: (uid: number) => Promise<any>;
                    setCard: (uid: number, card: string) => Promise<any>;
                    setAdmin: (uid: number, enable?: boolean) => Promise<any>;
                    setTitle: (uid: number, title: string, duration?: number) => Promise<any>;
                    quit: () => Promise<any>;
                    setName: (name: string) => Promise<any>;
                    muteAll: (enable?: boolean) => Promise<any>;
                    makeForwardMsg: (nodes: any[]) => any;
                    getInfo: () => Promise<any>;
                    getChatHistory: (seq: number, count?: number) => Promise<any>;
                    getFileUrl: (fid: string) => Promise<any>;
                    getAvatarUrl: (size?: 0 | 40 | 100 | 140) => string;
                    renew: () => Promise<any>;
                    readonly all_muted: boolean;
                    markRead: (seq?: number) => Promise<any>;
                    announce: (content: string) => Promise<any>;
                    allowAnony: (yes?: boolean) => Promise<any>;
                    setRemark: (remark?: string) => Promise<any>;
                    muteAnony: (flag: string, duration?: number) => Promise<any>;
                    getAnonyInfo: () => Promise<any>;
                    getAtAllRemainder: () => Promise<any>;
                    addEssence: (seq: number) => Promise<any>;
                    removeEssence: (seq: number) => Promise<any>;
                    sendFile: (file: any, _pid?: string, name?: string) => Promise<any>;
                    invite: (uid: number) => Promise<any>;
                    sign: () => Promise<any>;
                    setAvatar: (file: any) => Promise<any>;
                    setScreenMemberMsg: (memberId: number, isScreen?: boolean) => Promise<any>;
                    getMuteMemberList: () => Promise<any>;
                    fs: {
                        df: () => Promise<any>;
                        stat: (fid: string) => Promise<any>;
                        dir: (pid?: string, start?: number, limit?: number) => Promise<any[] | never[]>;
                        ls: (pid?: string, start?: number, limit?: number) => Promise<any[] | never[]>;
                        mkdir: (name: string) => Promise<any>;
                        rm: (fid: string) => Promise<any>;
                        rename: (fid: string, name: string) => Promise<any>;
                        mv: (fid: string, pid: string) => Promise<any>;
                        upload: (file: any, pid?: string, name?: string) => Promise<any>;
                        download: (fid: string) => Promise<any>;
                        readonly root_files: Promise<any[] | never[]>;
                    };
                };
                readonly info: Promise<any>;
                getInfo: (noCache?: boolean) => Promise<any>;
                renew: () => Promise<any>;
                setAdmin: (yes?: boolean) => Promise<any>;
                setTitle: (title?: string, duration?: number) => Promise<any>;
                setCard: (card?: string) => Promise<any>;
                kick: (_msg?: string, block?: boolean) => Promise<any>;
                mute: (duration?: number) => Promise<any>;
                poke: () => Promise<any>;
                addFriend: (comment?: string) => Promise<any>;
                setScreenMsg: (isScreen?: boolean) => Promise<any>;
                getAvatarUrl: () => string;
            };
            sendMsg: (msg: any) => Promise<any>;
            recallMsg: (messageId: any) => Promise<any>;
            getAvatarUrl: (size?: 0 | 40 | 100 | 140) => string;
            thumbUp: (times?: number) => Promise<any>;
            poke: (self?: boolean) => Promise<any>;
            getChatHistory: (time?: number, cnt?: number) => Promise<any>;
            markRead: (time?: number) => Promise<any>;
            getFileUrl: (fid: string) => Promise<any>;
            getFileInfo: (fid: string) => Promise<any>;
            sendFile: (file: any, filename?: string) => Promise<any>;
            recallFile: (fid: string) => Promise<any>;
            forwardFile: (fid: string, groupId?: number) => Promise<any>;
            delete: (block?: boolean) => Promise<any>;
            setRemark: (remark: string) => Promise<any>;
            setClass: (id: number) => Promise<any>;
            addFriendBack: (seq: number, remark?: string) => Promise<any>;
            setFriendReq: (seq: number, yes?: boolean, remark?: string) => Promise<any>;
            setGroupReq: (_gid: number, seq: number, yes?: boolean, reason?: string) => Promise<any>;
            setGroupInvite: (_gid: number, seq: number, yes?: boolean) => Promise<any>;
            getSimpleInfo: () => Promise<any>;
            getAddFriendSetting: () => Promise<any>;
            searchSameGroup: () => Promise<any>;
            makeForwardMsg: (nodes: any[]) => any;
        };
        pickGroup: (gid: number) => {
            group_id: number;
            readonly group_name: any;
            readonly name: any;
            readonly member_count: any;
            readonly max_member_count: any;
            is_owner: boolean;
            is_admin: boolean;
            mute_left: number;
            sendMsg: (msg: any) => Promise<any>;
            getMemberMap: () => Promise<Map<any, any>>;
            pickMember: (uid: number) => {
                user_id: number;
                group_id: number;
                readonly card: any;
                readonly nickname: any;
                readonly remark: any;
                readonly title: any;
                readonly role: any;
                readonly level: any;
                readonly is_admin: boolean;
                readonly is_owner: boolean;
                is_friend: boolean;
                readonly mute_left: number;
                readonly _info: any;
                group: any;
                readonly info: Promise<any>;
                getInfo: (noCache?: boolean) => Promise<any>;
                renew: () => Promise<any>;
                setAdmin: (yes?: boolean) => Promise<any>;
                setTitle: (title?: string, duration?: number) => Promise<any>;
                setCard: (card?: string) => Promise<any>;
                kick: (_msg?: string, block?: boolean) => Promise<any>;
                mute: (duration?: number) => Promise<any>;
                poke: () => Promise<any>;
                addFriend: (comment?: string) => Promise<any>;
                setScreenMsg: (isScreen?: boolean) => Promise<any>;
                getAvatarUrl: () => string;
            };
            recallMsg: (messageId: any) => Promise<any>;
            muteMember: (uid: number, duration?: number) => Promise<any>;
            kickMember: (uid: number, rejectAdd?: boolean) => Promise<any>;
            pokeMember: (uid: number) => Promise<any>;
            setCard: (uid: number, card: string) => Promise<any>;
            setAdmin: (uid: number, enable?: boolean) => Promise<any>;
            setTitle: (uid: number, title: string, duration?: number) => Promise<any>;
            quit: () => Promise<any>;
            setName: (name: string) => Promise<any>;
            muteAll: (enable?: boolean) => Promise<any>;
            makeForwardMsg: (nodes: any[]) => any;
            getInfo: () => Promise<any>;
            getChatHistory: (seq: number, count?: number) => Promise<any>;
            getFileUrl: (fid: string) => Promise<any>;
            getAvatarUrl: (size?: 0 | 40 | 100 | 140) => string;
            renew: () => Promise<any>;
            readonly all_muted: boolean;
            markRead: (seq?: number) => Promise<any>;
            announce: (content: string) => Promise<any>;
            allowAnony: (yes?: boolean) => Promise<any>;
            setRemark: (remark?: string) => Promise<any>;
            muteAnony: (flag: string, duration?: number) => Promise<any>;
            getAnonyInfo: () => Promise<any>;
            getAtAllRemainder: () => Promise<any>;
            addEssence: (seq: number) => Promise<any>;
            removeEssence: (seq: number) => Promise<any>;
            sendFile: (file: any, _pid?: string, name?: string) => Promise<any>;
            invite: (uid: number) => Promise<any>;
            sign: () => Promise<any>;
            setAvatar: (file: any) => Promise<any>;
            setScreenMemberMsg: (memberId: number, isScreen?: boolean) => Promise<any>;
            getMuteMemberList: () => Promise<any>;
            fs: {
                df: () => Promise<any>;
                stat: (fid: string) => Promise<any>;
                dir: (pid?: string, start?: number, limit?: number) => Promise<any[] | never[]>;
                ls: (pid?: string, start?: number, limit?: number) => Promise<any[] | never[]>;
                mkdir: (name: string) => Promise<any>;
                rm: (fid: string) => Promise<any>;
                rename: (fid: string, name: string) => Promise<any>;
                mv: (fid: string, pid: string) => Promise<any>;
                upload: (file: any, pid?: string, name?: string) => Promise<any>;
                download: (fid: string) => Promise<any>;
                readonly root_files: Promise<any[] | never[]>;
            };
        };
        pickUser: (uid: number) => {
            user_id: number;
            readonly nickname: any;
            readonly remark: any;
            readonly info: any;
            readonly sex: any;
            readonly class_id: any;
            readonly class_name: any;
            asFriend: () => any;
            asMember: (gid: number) => {
                user_id: number;
                group_id: number;
                readonly card: any;
                readonly nickname: any;
                readonly remark: any;
                readonly title: any;
                readonly role: any;
                readonly level: any;
                readonly is_admin: boolean;
                readonly is_owner: boolean;
                is_friend: boolean;
                readonly mute_left: number;
                readonly _info: any;
                group: {
                    group_id: number;
                    readonly group_name: any;
                    readonly name: any;
                    readonly member_count: any;
                    readonly max_member_count: any;
                    is_owner: boolean;
                    is_admin: boolean;
                    mute_left: number;
                    sendMsg: (msg: any) => Promise<any>;
                    getMemberMap: () => Promise<Map<any, any>>;
                    pickMember: (uid: number) => any;
                    recallMsg: (messageId: any) => Promise<any>;
                    muteMember: (uid: number, duration?: number) => Promise<any>;
                    kickMember: (uid: number, rejectAdd?: boolean) => Promise<any>;
                    pokeMember: (uid: number) => Promise<any>;
                    setCard: (uid: number, card: string) => Promise<any>;
                    setAdmin: (uid: number, enable?: boolean) => Promise<any>;
                    setTitle: (uid: number, title: string, duration?: number) => Promise<any>;
                    quit: () => Promise<any>;
                    setName: (name: string) => Promise<any>;
                    muteAll: (enable?: boolean) => Promise<any>;
                    makeForwardMsg: (nodes: any[]) => any;
                    getInfo: () => Promise<any>;
                    getChatHistory: (seq: number, count?: number) => Promise<any>;
                    getFileUrl: (fid: string) => Promise<any>;
                    getAvatarUrl: (size?: 0 | 40 | 100 | 140) => string;
                    renew: () => Promise<any>;
                    readonly all_muted: boolean;
                    markRead: (seq?: number) => Promise<any>;
                    announce: (content: string) => Promise<any>;
                    allowAnony: (yes?: boolean) => Promise<any>;
                    setRemark: (remark?: string) => Promise<any>;
                    muteAnony: (flag: string, duration?: number) => Promise<any>;
                    getAnonyInfo: () => Promise<any>;
                    getAtAllRemainder: () => Promise<any>;
                    addEssence: (seq: number) => Promise<any>;
                    removeEssence: (seq: number) => Promise<any>;
                    sendFile: (file: any, _pid?: string, name?: string) => Promise<any>;
                    invite: (uid: number) => Promise<any>;
                    sign: () => Promise<any>;
                    setAvatar: (file: any) => Promise<any>;
                    setScreenMemberMsg: (memberId: number, isScreen?: boolean) => Promise<any>;
                    getMuteMemberList: () => Promise<any>;
                    fs: {
                        df: () => Promise<any>;
                        stat: (fid: string) => Promise<any>;
                        dir: (pid?: string, start?: number, limit?: number) => Promise<any[] | never[]>;
                        ls: (pid?: string, start?: number, limit?: number) => Promise<any[] | never[]>;
                        mkdir: (name: string) => Promise<any>;
                        rm: (fid: string) => Promise<any>;
                        rename: (fid: string, name: string) => Promise<any>;
                        mv: (fid: string, pid: string) => Promise<any>;
                        upload: (file: any, pid?: string, name?: string) => Promise<any>;
                        download: (fid: string) => Promise<any>;
                        readonly root_files: Promise<any[] | never[]>;
                    };
                };
                readonly info: Promise<any>;
                getInfo: (noCache?: boolean) => Promise<any>;
                renew: () => Promise<any>;
                setAdmin: (yes?: boolean) => Promise<any>;
                setTitle: (title?: string, duration?: number) => Promise<any>;
                setCard: (card?: string) => Promise<any>;
                kick: (_msg?: string, block?: boolean) => Promise<any>;
                mute: (duration?: number) => Promise<any>;
                poke: () => Promise<any>;
                addFriend: (comment?: string) => Promise<any>;
                setScreenMsg: (isScreen?: boolean) => Promise<any>;
                getAvatarUrl: () => string;
            };
            sendMsg: (msg: any) => Promise<any>;
            recallMsg: (messageId: any) => Promise<any>;
            getAvatarUrl: (size?: 0 | 40 | 100 | 140) => string;
            thumbUp: (times?: number) => Promise<any>;
            poke: (self?: boolean) => Promise<any>;
            getChatHistory: (time?: number, cnt?: number) => Promise<any>;
            markRead: (time?: number) => Promise<any>;
            getFileUrl: (fid: string) => Promise<any>;
            getFileInfo: (fid: string) => Promise<any>;
            sendFile: (file: any, filename?: string) => Promise<any>;
            recallFile: (fid: string) => Promise<any>;
            forwardFile: (fid: string, groupId?: number) => Promise<any>;
            delete: (block?: boolean) => Promise<any>;
            setRemark: (remark: string) => Promise<any>;
            setClass: (id: number) => Promise<any>;
            addFriendBack: (seq: number, remark?: string) => Promise<any>;
            setFriendReq: (seq: number, yes?: boolean, remark?: string) => Promise<any>;
            setGroupReq: (_gid: number, seq: number, yes?: boolean, reason?: string) => Promise<any>;
            setGroupInvite: (_gid: number, seq: number, yes?: boolean) => Promise<any>;
            getSimpleInfo: () => Promise<any>;
            getAddFriendSetting: () => Promise<any>;
            searchSameGroup: () => Promise<any>;
            makeForwardMsg: (nodes: any[]) => any;
        };
        pickMember: (gid: number, uid: number) => {
            user_id: number;
            group_id: number;
            readonly card: any;
            readonly nickname: any;
            readonly remark: any;
            readonly title: any;
            readonly role: any;
            readonly level: any;
            readonly is_admin: boolean;
            readonly is_owner: boolean;
            is_friend: boolean;
            readonly mute_left: number;
            readonly _info: any;
            group: {
                group_id: number;
                readonly group_name: any;
                readonly name: any;
                readonly member_count: any;
                readonly max_member_count: any;
                is_owner: boolean;
                is_admin: boolean;
                mute_left: number;
                sendMsg: (msg: any) => Promise<any>;
                getMemberMap: () => Promise<Map<any, any>>;
                pickMember: (uid: number) => any;
                recallMsg: (messageId: any) => Promise<any>;
                muteMember: (uid: number, duration?: number) => Promise<any>;
                kickMember: (uid: number, rejectAdd?: boolean) => Promise<any>;
                pokeMember: (uid: number) => Promise<any>;
                setCard: (uid: number, card: string) => Promise<any>;
                setAdmin: (uid: number, enable?: boolean) => Promise<any>;
                setTitle: (uid: number, title: string, duration?: number) => Promise<any>;
                quit: () => Promise<any>;
                setName: (name: string) => Promise<any>;
                muteAll: (enable?: boolean) => Promise<any>;
                makeForwardMsg: (nodes: any[]) => any;
                getInfo: () => Promise<any>;
                getChatHistory: (seq: number, count?: number) => Promise<any>;
                getFileUrl: (fid: string) => Promise<any>;
                getAvatarUrl: (size?: 0 | 40 | 100 | 140) => string;
                renew: () => Promise<any>;
                readonly all_muted: boolean;
                markRead: (seq?: number) => Promise<any>;
                announce: (content: string) => Promise<any>;
                allowAnony: (yes?: boolean) => Promise<any>;
                setRemark: (remark?: string) => Promise<any>;
                muteAnony: (flag: string, duration?: number) => Promise<any>;
                getAnonyInfo: () => Promise<any>;
                getAtAllRemainder: () => Promise<any>;
                addEssence: (seq: number) => Promise<any>;
                removeEssence: (seq: number) => Promise<any>;
                sendFile: (file: any, _pid?: string, name?: string) => Promise<any>;
                invite: (uid: number) => Promise<any>;
                sign: () => Promise<any>;
                setAvatar: (file: any) => Promise<any>;
                setScreenMemberMsg: (memberId: number, isScreen?: boolean) => Promise<any>;
                getMuteMemberList: () => Promise<any>;
                fs: {
                    df: () => Promise<any>;
                    stat: (fid: string) => Promise<any>;
                    dir: (pid?: string, start?: number, limit?: number) => Promise<any[] | never[]>;
                    ls: (pid?: string, start?: number, limit?: number) => Promise<any[] | never[]>;
                    mkdir: (name: string) => Promise<any>;
                    rm: (fid: string) => Promise<any>;
                    rename: (fid: string, name: string) => Promise<any>;
                    mv: (fid: string, pid: string) => Promise<any>;
                    upload: (file: any, pid?: string, name?: string) => Promise<any>;
                    download: (fid: string) => Promise<any>;
                    readonly root_files: Promise<any[] | never[]>;
                };
            };
            readonly info: Promise<any>;
            getInfo: (noCache?: boolean) => Promise<any>;
            renew: () => Promise<any>;
            setAdmin: (yes?: boolean) => Promise<any>;
            setTitle: (title?: string, duration?: number) => Promise<any>;
            setCard: (card?: string) => Promise<any>;
            kick: (_msg?: string, block?: boolean) => Promise<any>;
            mute: (duration?: number) => Promise<any>;
            poke: () => Promise<any>;
            addFriend: (comment?: string) => Promise<any>;
            setScreenMsg: (isScreen?: boolean) => Promise<any>;
            getAvatarUrl: () => string;
        };
        sendGroupMsg: (gid: number, msg: any) => Promise<any>;
        sendPrivateMsg: (uid: number, msg: any) => Promise<any>;
        getGroupList: () => Promise<Map<any, any>>;
        getFriendList: () => Promise<Map<any, any>>;
        getStrangerInfo: (uid: number) => Promise<any>;
        getLoginInfo: () => Promise<{
            user_id: any;
            nickname: string;
        } | {
            user_id: any;
            nickname: string;
        }>;
        getGroupMemberList: (gid: number) => Promise<Map<any, any>>;
        getGroupMemberInfo: (gid: number, uid: number) => Promise<any>;
        getForwardMsg: (resId: string) => Promise<any>;
        getCookies: (domain?: string) => Promise<any>;
        getCsrfToken: () => Promise<any>;
        sendLike: (uid: number, times?: number) => Promise<any>;
        getStrangerList: () => Promise<any>;
        reloadFriendList: () => any;
        reloadGroupList: () => any;
        reloadBlackList: () => Promise<any>;
        setOnlineStatus: (status: number) => Promise<any>;
        setNickname: (nickname: string) => Promise<any>;
        setGender: (gender: number) => Promise<any>;
        setBirthday: (birthday: string) => Promise<any>;
        setDescription: (description: string) => Promise<any>;
        setSignature: (signature: string) => Promise<any>;
        setAvatar: (file: any) => Promise<any>;
        getSignature: () => Promise<any>;
        imageOcr: (image: string) => Promise<any>;
        getVideoUrl: (fid: string, md5: string) => Promise<any>;
        getSystemMsg: () => Promise<any>;
        setEssenceMessage: (messageId: number) => Promise<any>;
        removeEssenceMessage: (messageId: number) => Promise<any>;
        getRoamingStamp: () => Promise<any>;
        deleteStamp: (id: string) => Promise<any>;
        cleanCache: () => Promise<any>;
        addClass: (name: string) => Promise<any>;
        deleteClass: (id: number) => Promise<any>;
        renameClass: (id: number, name: string) => Promise<any>;
        makeForwardMsg: (msgs: any[]) => any;
    };
    createOneBotGroupAdapter: (groupId: number, opts?: OneBotGroupOptions) => {
        group_id: number;
        readonly group_name: any;
        readonly name: any;
        readonly member_count: any;
        readonly max_member_count: any;
        is_owner: boolean;
        is_admin: boolean;
        mute_left: number;
        sendMsg: (msg: any) => Promise<any>;
        getMemberMap: () => Promise<Map<any, any>>;
        pickMember: (uid: number) => {
            user_id: number;
            group_id: number;
            readonly card: any;
            readonly nickname: any;
            readonly remark: any;
            readonly title: any;
            readonly role: any;
            readonly level: any;
            readonly is_admin: boolean;
            readonly is_owner: boolean;
            is_friend: boolean;
            readonly mute_left: number;
            readonly _info: any;
            group: any;
            readonly info: Promise<any>;
            getInfo: (noCache?: boolean) => Promise<any>;
            renew: () => Promise<any>;
            setAdmin: (yes?: boolean) => Promise<any>;
            setTitle: (title?: string, duration?: number) => Promise<any>;
            setCard: (card?: string) => Promise<any>;
            kick: (_msg?: string, block?: boolean) => Promise<any>;
            mute: (duration?: number) => Promise<any>;
            poke: () => Promise<any>;
            addFriend: (comment?: string) => Promise<any>;
            setScreenMsg: (isScreen?: boolean) => Promise<any>;
            getAvatarUrl: () => string;
        };
        recallMsg: (messageId: any) => Promise<any>;
        muteMember: (uid: number, duration?: number) => Promise<any>;
        kickMember: (uid: number, rejectAdd?: boolean) => Promise<any>;
        pokeMember: (uid: number) => Promise<any>;
        setCard: (uid: number, card: string) => Promise<any>;
        setAdmin: (uid: number, enable?: boolean) => Promise<any>;
        setTitle: (uid: number, title: string, duration?: number) => Promise<any>;
        quit: () => Promise<any>;
        setName: (name: string) => Promise<any>;
        muteAll: (enable?: boolean) => Promise<any>;
        makeForwardMsg: (nodes: any[]) => any;
        getInfo: () => Promise<any>;
        getChatHistory: (seq: number, count?: number) => Promise<any>;
        getFileUrl: (fid: string) => Promise<any>;
        getAvatarUrl: (size?: 0 | 40 | 100 | 140) => string;
        renew: () => Promise<any>;
        readonly all_muted: boolean;
        markRead: (seq?: number) => Promise<any>;
        announce: (content: string) => Promise<any>;
        allowAnony: (yes?: boolean) => Promise<any>;
        setRemark: (remark?: string) => Promise<any>;
        muteAnony: (flag: string, duration?: number) => Promise<any>;
        getAnonyInfo: () => Promise<any>;
        getAtAllRemainder: () => Promise<any>;
        addEssence: (seq: number) => Promise<any>;
        removeEssence: (seq: number) => Promise<any>;
        sendFile: (file: any, _pid?: string, name?: string) => Promise<any>;
        invite: (uid: number) => Promise<any>;
        sign: () => Promise<any>;
        setAvatar: (file: any) => Promise<any>;
        setScreenMemberMsg: (memberId: number, isScreen?: boolean) => Promise<any>;
        getMuteMemberList: () => Promise<any>;
        fs: {
            df: () => Promise<any>;
            stat: (fid: string) => Promise<any>;
            dir: (pid?: string, start?: number, limit?: number) => Promise<any[] | never[]>;
            ls: (pid?: string, start?: number, limit?: number) => Promise<any[] | never[]>;
            mkdir: (name: string) => Promise<any>;
            rm: (fid: string) => Promise<any>;
            rename: (fid: string, name: string) => Promise<any>;
            mv: (fid: string, pid: string) => Promise<any>;
            upload: (file: any, pid?: string, name?: string) => Promise<any>;
            download: (fid: string) => Promise<any>;
            readonly root_files: Promise<any[] | never[]>;
        };
    };
    createOneBotFriendAdapter: (userId: number, userName: string) => {
        user_id: number;
        readonly nickname: any;
        readonly remark: any;
        readonly info: any;
        readonly sex: any;
        readonly class_id: any;
        readonly class_name: any;
        asFriend: () => any;
        asMember: (gid: number) => {
            user_id: number;
            group_id: number;
            readonly card: any;
            readonly nickname: any;
            readonly remark: any;
            readonly title: any;
            readonly role: any;
            readonly level: any;
            readonly is_admin: boolean;
            readonly is_owner: boolean;
            is_friend: boolean;
            readonly mute_left: number;
            readonly _info: any;
            group: {
                group_id: number;
                readonly group_name: any;
                readonly name: any;
                readonly member_count: any;
                readonly max_member_count: any;
                is_owner: boolean;
                is_admin: boolean;
                mute_left: number;
                sendMsg: (msg: any) => Promise<any>;
                getMemberMap: () => Promise<Map<any, any>>;
                pickMember: (uid: number) => any;
                recallMsg: (messageId: any) => Promise<any>;
                muteMember: (uid: number, duration?: number) => Promise<any>;
                kickMember: (uid: number, rejectAdd?: boolean) => Promise<any>;
                pokeMember: (uid: number) => Promise<any>;
                setCard: (uid: number, card: string) => Promise<any>;
                setAdmin: (uid: number, enable?: boolean) => Promise<any>;
                setTitle: (uid: number, title: string, duration?: number) => Promise<any>;
                quit: () => Promise<any>;
                setName: (name: string) => Promise<any>;
                muteAll: (enable?: boolean) => Promise<any>;
                makeForwardMsg: (nodes: any[]) => any;
                getInfo: () => Promise<any>;
                getChatHistory: (seq: number, count?: number) => Promise<any>;
                getFileUrl: (fid: string) => Promise<any>;
                getAvatarUrl: (size?: 0 | 40 | 100 | 140) => string;
                renew: () => Promise<any>;
                readonly all_muted: boolean;
                markRead: (seq?: number) => Promise<any>;
                announce: (content: string) => Promise<any>;
                allowAnony: (yes?: boolean) => Promise<any>;
                setRemark: (remark?: string) => Promise<any>;
                muteAnony: (flag: string, duration?: number) => Promise<any>;
                getAnonyInfo: () => Promise<any>;
                getAtAllRemainder: () => Promise<any>;
                addEssence: (seq: number) => Promise<any>;
                removeEssence: (seq: number) => Promise<any>;
                sendFile: (file: any, _pid?: string, name?: string) => Promise<any>;
                invite: (uid: number) => Promise<any>;
                sign: () => Promise<any>;
                setAvatar: (file: any) => Promise<any>;
                setScreenMemberMsg: (memberId: number, isScreen?: boolean) => Promise<any>;
                getMuteMemberList: () => Promise<any>;
                fs: {
                    df: () => Promise<any>;
                    stat: (fid: string) => Promise<any>;
                    dir: (pid?: string, start?: number, limit?: number) => Promise<any[] | never[]>;
                    ls: (pid?: string, start?: number, limit?: number) => Promise<any[] | never[]>;
                    mkdir: (name: string) => Promise<any>;
                    rm: (fid: string) => Promise<any>;
                    rename: (fid: string, name: string) => Promise<any>;
                    mv: (fid: string, pid: string) => Promise<any>;
                    upload: (file: any, pid?: string, name?: string) => Promise<any>;
                    download: (fid: string) => Promise<any>;
                    readonly root_files: Promise<any[] | never[]>;
                };
            };
            readonly info: Promise<any>;
            getInfo: (noCache?: boolean) => Promise<any>;
            renew: () => Promise<any>;
            setAdmin: (yes?: boolean) => Promise<any>;
            setTitle: (title?: string, duration?: number) => Promise<any>;
            setCard: (card?: string) => Promise<any>;
            kick: (_msg?: string, block?: boolean) => Promise<any>;
            mute: (duration?: number) => Promise<any>;
            poke: () => Promise<any>;
            addFriend: (comment?: string) => Promise<any>;
            setScreenMsg: (isScreen?: boolean) => Promise<any>;
            getAvatarUrl: () => string;
        };
        sendMsg: (msg: any) => Promise<any>;
        recallMsg: (messageId: any) => Promise<any>;
        getAvatarUrl: (size?: 0 | 40 | 100 | 140) => string;
        thumbUp: (times?: number) => Promise<any>;
        poke: (self?: boolean) => Promise<any>;
        getChatHistory: (time?: number, cnt?: number) => Promise<any>;
        markRead: (time?: number) => Promise<any>;
        getFileUrl: (fid: string) => Promise<any>;
        getFileInfo: (fid: string) => Promise<any>;
        sendFile: (file: any, filename?: string) => Promise<any>;
        recallFile: (fid: string) => Promise<any>;
        forwardFile: (fid: string, groupId?: number) => Promise<any>;
        delete: (block?: boolean) => Promise<any>;
        setRemark: (remark: string) => Promise<any>;
        setClass: (id: number) => Promise<any>;
        addFriendBack: (seq: number, remark?: string) => Promise<any>;
        setFriendReq: (seq: number, yes?: boolean, remark?: string) => Promise<any>;
        setGroupReq: (_gid: number, seq: number, yes?: boolean, reason?: string) => Promise<any>;
        setGroupInvite: (_gid: number, seq: number, yes?: boolean) => Promise<any>;
        getSimpleInfo: () => Promise<any>;
        getAddFriendSetting: () => Promise<any>;
        searchSameGroup: () => Promise<any>;
        makeForwardMsg: (nodes: any[]) => any;
    };
    buildOneBotEvent: ({ data, msgId, selfId, reply }: BuildOneBotEventOptions) => any;
    normalizeFriendRecord: (friend: any) => any;
    normalizeGroupRecord: (group: any) => any;
    normalizeMemberRecord: (member: any) => any;
};
export {};
